name: Android APK Build

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:  # Manuel çalıştırma butonu

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Kodu indir
        uses: actions/checkout@v3

      - name: Java kur
        uses: actions/upload-artifact@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Android SDK kur
        uses: android-actions/setup-android@v2

      - name: Gradle iznini ver
        run: chmod +x gradlew

      - name: APK derle
        run: ./gradlew assembleDebug

      - name: APK'yı kaydet
        uses: actions/upload-artifact@v3
        with:
          name: DavutGulecApp-APK
          path: app/build/outputs/apk/debug/app-debug.apk
